# config.yaml
project:
  name: "e2e-ml-pipeline"
  experiment_name: "e2e-ml-pipeline"
  model_name: "e2e-ml-pipeline"

data:
  path: "./data/dev/train/wine-quality-white.csv"
  target_column: "quality"
  test_size: 0.30
  random_state: 42

mlflow:
  tracking_uri: "http://localhost:5000"
  model_stage: "production"
  server_port: 5000

logging:
  level: "INFO"